import Head from "next/head";
import React, { useEffect, useState } from "react";
import { DateTime } from "luxon";
import Light from "~/components/Light";
import * as tf from "@tensorflow/tfjs";
import {
  loadMobileNetFeatureModel,
  initializeModel,
} from "~/utilities/useModel";
import WebCamera from "~/components/WebCamera";

export default function Home() {
  const [startGame, setStartGame] = useState(false);
  const [buffer, setBuffer] = useState(Math.random() * (5 - 1.6) + 1.6);

  interface Models {
    mobilenet: tf.GraphModel | null;
    model: tf.LayersModel | null;
  }

  const [models, setModels] = useState<Models>({
    mobilenet: null,
    model: null,
  });

  useEffect(() => {
    const loadModels = async (): Promise<void> => {
      const mobilenet = await loadMobileNetFeatureModel();
      const model = initializeModel();
      setModels({ mobilenet, model });
    };

    loadModels();
  }, []);

  const handleStart = () => {
    setStartGame(true);
  };

  return (
    <>
      <Head>
        <title>Lights</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center">
        <button
          onClick={handleStart}
          className="animate-pulse bg-white px-8 py-3"
        >
          Start
        </button>{" "}
        <div className="flex h-screen w-full flex-col items-center justify-center py-8">

          <WebCamera
            startGame={startGame}
            buffer={buffer}
            mobilenet={models.mobilenet}
            model={models.model}
          />
        </div>
      </main>
    </>
  );
}
